MODEL:
  VALID_SCALE: [0, 1, 2]
SOLVER:
  BATCH_SIZE: 2
  DETECTOR:
    INIT_TRAIN_ITER: 900000
    ADV_LOSS_WEIGHT: 0.
  DISCRIMINATOR:
    INIT_TRAIN_ITER: 0
    # GP: True
  DATA:
    BOX_THRESHOLD: [0.3, 0.95, 0.95]
