MODEL:
  VALID_SCALE: [2]
SOLVER:
  BATCH_SIZE: 32
  DETECTOR:
    INIT_TRAIN_ITER: 900000
    ADV_LOSS_WEIGHT: 0.
  DISCRIMINATOR:
    INIT_TRAIN_ITER: 0
    # GP: True
  DATA:
    BOX_THRESHOLD: 0.3

# DATASET:
#   TRAIN: ('coco_2014_minival',)